// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"DarkPlasma_ChoiceHelp","status":true,"description":"選択肢にヘルプを表示する","parameters":{}},
{"name":"Mano_ChoiceCustom","status":true,"description":"選択肢で様々なことを可能にします。","parameters":{}}
];
